include("hotkey.jl")

hotkeys = Hotkey[
    Hotkey(
        's',
        menuFileSave,
        Function[
            modifierControl
        ]
    ),
    Hotkey(
        'S',
        showFileSaveDialog,
        Function[
            modifierControl,
            modifierShift
        ]
    ),
    Hotkey(
        'o',
        showFileOpenDialog,
        Function[
            modifierControl
        ]
    ),
    Hotkey(
        't',
        RoomWindow.createRoom,
        Function[
            modifierControl
        ]
    ),
    Hotkey(
        'T',
        RoomWindow.configureRoom,
        Function[
            modifierControl,
            modifierShift
        ]
    ),
    Hotkey(
        'z',
        History.undo!,
        Function[
            modifierControl
        ]
    ),
    Hotkey(
        'Z',
        History.redo!,
        Function[
            modifierControl,
            modifierShift
        ]
    ),
    Hotkey(
        'f',
        focusFilterEntry!,
        Function[
            modifierControl
        ]
    )
]